# Generated by Django 5.2.7 on 2025-10-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_booking_user_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='img', upload_to='media/'),
            preserve_default=False,
        ),
    ]
